### ISSUE TITLE
Light sensor returns higher value at darker light

### ISSUE THREAD

**Issue by dhineshkumarmcci** [mcci-catena/Catena-Arduino-Platform#273]
At darker (low-light) region, Si1133 returns channel data as FFFFxx on read. Instead it should return zero.

**Comment by terrillmoore** [comment]
We speculate that this is due to dark current being slightly higher than the actual current from the measurement photodiode, due to noise, physical variation across the die, or similar. We think that the Si1133 measures the current from the measurement diode, then measures and subtracts the current from the dark-current photodiode, and doesn't prevent the result from going negative. The "24 bit" measurement mode is in fact a signed measurement (the saturation value is 0x7FFFFF, according to the datasheet), and the dark current is pretty small; we can treat any value in 0x800000 .. 0xFFFFFF as being negative; since light can't be negative, we can substitute zero.
